<?php

namespace Proxies\__CG__\JOYAS\JoyasBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Cliente extends \JOYAS\JoyasBundle\Entity\Cliente implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setRazonSocial($razonSocial)
    {
        $this->__load();
        return parent::setRazonSocial($razonSocial);
    }

    public function getRazonSocial()
    {
        $this->__load();
        return parent::getRazonSocial();
    }

    public function setCuit($cuit)
    {
        $this->__load();
        return parent::setCuit($cuit);
    }

    public function getCuit()
    {
        $this->__load();
        return parent::getCuit();
    }

    public function setDni($dni)
    {
        $this->__load();
        return parent::setDni($dni);
    }

    public function getDni()
    {
        $this->__load();
        return parent::getDni();
    }

    public function setDomiciliocomercial($domiciliocomercial)
    {
        $this->__load();
        return parent::setDomiciliocomercial($domiciliocomercial);
    }

    public function getDomiciliocomercial()
    {
        $this->__load();
        return parent::getDomiciliocomercial();
    }

    public function setTelefono($telefono)
    {
        $this->__load();
        return parent::setTelefono($telefono);
    }

    public function getTelefono()
    {
        $this->__load();
        return parent::getTelefono();
    }

    public function setMail($mail)
    {
        $this->__load();
        return parent::setMail($mail);
    }

    public function getMail()
    {
        $this->__load();
        return parent::getMail();
    }

    public function setClienteProveedor($clienteProveedor)
    {
        $this->__load();
        return parent::setClienteProveedor($clienteProveedor);
    }

    public function getClienteProveedor()
    {
        $this->__load();
        return parent::getClienteProveedor();
    }

    public function setEstado($estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function setCondicioniva(\JOYAS\JoyasBundle\Entity\CondicionIva $condicioniva = NULL)
    {
        $this->__load();
        return parent::setCondicioniva($condicioniva);
    }

    public function getCondicioniva()
    {
        $this->__load();
        return parent::getCondicioniva();
    }

    public function setConcepto($concepto)
    {
        $this->__load();
        return parent::setConcepto($concepto);
    }

    public function getConcepto()
    {
        $this->__load();
        return parent::getConcepto();
    }

    public function setMonto($monto)
    {
        $this->__load();
        return parent::setMonto($monto);
    }

    public function getMonto()
    {
        $this->__load();
        return parent::getMonto();
    }

    public function addFactura(\JOYAS\JoyasBundle\Entity\Factura $facturas)
    {
        $this->__load();
        return parent::addFactura($facturas);
    }

    public function removeFactura(\JOYAS\JoyasBundle\Entity\Factura $facturas)
    {
        $this->__load();
        return parent::removeFactura($facturas);
    }

    public function getFacturas()
    {
        $this->__load();
        return parent::getFacturas();
    }

    public function setUsuario(\JOYAS\JoyasBundle\Entity\Usuario $usuario)
    {
        $this->__load();
        return parent::setUsuario($usuario);
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'razonSocial', 'cuit', 'dni', 'domiciliocomercial', 'concepto', 'monto', 'telefono', 'mail', 'clienteProveedor', 'estado', 'condicioniva', 'facturas', 'usuario');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}