<?php

namespace JOYAS\JoyasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CondicionIvaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CondicionIvaRepository extends EntityRepository
{
}
