<?php

namespace JOYAS\JoyasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends EntityRepository
{
	public function getAllActivas($unidad = NULL){
		if(isset($unidad)){
			$query = $this->getEntityManager()->createQuery('SELECT e FROM JOYAS\JoyasBundle\Entity\Producto e WHERE e.estado = :activo and e.codigo != :codigo AND e.unidadNegocio = :unidad ORDER BY e.codigo ASC')->setParameter(':activo','A')->setParameter(':codigo','000')->setParameter(':unidad',$unidad);
		}else{
			$query = $this->getEntityManager()->createQuery('SELECT e FROM JOYAS\JoyasBundle\Entity\Producto e WHERE e.estado = :activo and e.codigo != :codigo ORDER BY e.codigo ASC')->setParameter(':activo','A')->setParameter(':codigo','000');
		}
		return $query->getResult();
	}

	public function getAllVisibles(){
		$query = $this->getEntityManager()->createQuery('SELECT e FROM JOYAS\JoyasBundle\Entity\Producto e WHERE e.estado = :activo and e.visible = 1 ORDER BY e.id DESC')->setParameter(':activo','A');
		return $query->getResult();
	}	
	public function relacionados($idcatsub){
		$query = $this->getEntityManager()->createQuery('SELECT pr FROM JOYAS\JoyasBundle\Entity\Producto e, JOYAS\JoyasBundle\Entity\Precio pr, JOYAS\JoyasBundle\Entity\ListaPrecio lp WHERE e.id = pr.producto AND pr.listaPrecio = lp.id AND lp.descripcion = :desclista AND e.categoriasubcategoria = :idcatsub AND e.visible = 1 AND e.estado = :activo')->setParameter(':activo','A')->setParameter(':idcatsub',$idcatsub)->setParameter(':desclista','Lista Web');
		return $query->getResult();
	}
	public function porcategoria($idcat){
		$query = $this->getEntityManager()->createQuery('SELECT pr FROM JOYAS\JoyasBundle\Entity\Producto e, JOYAS\JoyasBundle\Entity\Precio pr, JOYAS\JoyasBundle\Entity\ListaPrecio lp, JOYAS\JoyasBundle\Entity\Categoriasubcategoria cs WHERE e.id = pr.producto AND pr.listaPrecio = lp.id AND lp.descripcion = :desclista AND e.categoriasubcategoria = cs.id AND cs.categoria = :idcat  AND e.visible = 1 AND e.estado = :activo ORDER BY e.novedad DESC')->setParameter(':activo','A')->setParameter(':idcat',$idcat)->setParameter(':desclista','Lista Web');
		return $query->getResult();
	}

	public function porcategoriayprecio($idcat, $ini, $fin){
		$query = $this->getEntityManager()->createQuery('SELECT pr FROM JOYAS\JoyasBundle\Entity\Producto e, JOYAS\JoyasBundle\Entity\Precio pr, JOYAS\JoyasBundle\Entity\ListaPrecio lp, JOYAS\JoyasBundle\Entity\Categoriasubcategoria cs WHERE e.id = pr.producto AND pr.listaPrecio = lp.id AND lp.descripcion = :desclista AND e.categoriasubcategoria = cs.id AND cs.categoria = :idcat  AND e.visible = 1 AND e.estado = :activo AND pr.valor >= :ini AND pr.valor <= :fin ORDER BY e.novedad DESC')->setParameter(':activo','A')->setParameter(':idcat',$idcat)->setParameter(':desclista','Lista Web')->setParameter(':ini',$ini)->setParameter(':fin',$fin);
		return $query->getResult();
	}

	public function novedadesxprecio($ini, $fin){
		$query = $this->getEntityManager()->createQuery('SELECT pr FROM JOYAS\JoyasBundle\Entity\Producto e, JOYAS\JoyasBundle\Entity\Precio pr, JOYAS\JoyasBundle\Entity\ListaPrecio lp WHERE e.id = pr.producto AND pr.listaPrecio = lp.id AND lp.descripcion = :desclista AND e.novedad = 1 AND e.visible = 1 AND e.estado = :activo AND pr.valor >= :ini AND pr.valor <= :fin ORDER BY e.id DESC')->setParameter(':activo','A')->setParameter(':desclista','Lista Web')->setParameter(':ini',$ini)->setParameter(':fin',$fin);
		return $query->getResult();
	}
	public function ofertasxprecio($ini, $fin){
		$query = $this->getEntityManager()->createQuery('SELECT pr FROM JOYAS\JoyasBundle\Entity\Producto e, JOYAS\JoyasBundle\Entity\Precio pr, JOYAS\JoyasBundle\Entity\ListaPrecio lp WHERE e.id = pr.producto AND pr.listaPrecio = lp.id AND lp.descripcion = :desclista AND e.descuento != :vacio AND e.descuento > 0 AND e.visible = 1 AND e.estado = :activo AND pr.valor >= :ini AND pr.valor <= :fin ORDER BY e.id DESC')->setParameter(':activo','A')->setParameter(':desclista','Lista Web')->setParameter(':ini',$ini)->setParameter(':fin',$fin)->setParameter(':vacio','');
		return $query->getResult();
	}

	public function novedades(){
		$query = $this->getEntityManager()->createQuery('SELECT pr FROM JOYAS\JoyasBundle\Entity\Producto e, JOYAS\JoyasBundle\Entity\Precio pr, JOYAS\JoyasBundle\Entity\ListaPrecio lp WHERE e.id = pr.producto AND pr.listaPrecio = lp.id AND lp.descripcion = :desclista AND e.novedad = 1 AND e.visible = 1 AND e.estado = :activo ORDER BY e.novedad DESC')->setParameter(':activo','A')->setParameter(':desclista','Lista Web');
		return $query->getResult();
	}
	
	public function ofertas(){
		$query = $this->getEntityManager()->createQuery('
			SELECT pr 
			FROM JOYAS\JoyasBundle\Entity\Producto e, JOYAS\JoyasBundle\Entity\Precio pr, JOYAS\JoyasBundle\Entity\ListaPrecio lp 
			WHERE e.id = pr.producto 
			AND pr.listaPrecio = lp.id 
			AND lp.descripcion = :desclista 
			AND e.descuento != :vacio 
			AND e.descuento > 0 
			AND e.visible = 1 
			AND e.estado = :activo ORDER BY e.descuento DESC')->setParameter(':activo','A')->setParameter(':desclista','Lista Web')->setParameter(':vacio','');
		return $query->getResult();
	}
	
	public function precios($id){
		$query = $this->getEntityManager()->createQuery('SELECT pr FROM JOYAS\JoyasBundle\Entity\Precio pr WHERE pr.listaPrecio = :idLista ORDER BY pr.producto DESC')->setParameter(':idLista',$id);
		return $query;
	}
	
	public function porbusqueda($busc){
		$query = $this->getEntityManager()->createQuery('
		SELECT pr FROM JOYAS\JoyasBundle\Entity\Producto e, JOYAS\JoyasBundle\Entity\Precio pr, JOYAS\JoyasBundle\Entity\ListaPrecio lp 
		WHERE e.id = pr.producto 
		AND	  pr.listaPrecio = lp.id 
		AND lp.descripcion = :desclista 
		AND (e.descripcion LIKE :busc OR e.codigo LIKE :busc)
		AND e.visible = 1 
		AND e.estado = :activo
		')->setParameter(':activo','A')->setParameter(':busc','%'.$busc.'%')->setParameter(':desclista','Lista Web');
		return $query->getResult();
	}
	public function predictiva($src){
		$query = $this->getEntityManager()->createQuery('
        SELECT e 
        FROM JOYAS\JoyasBundle\Entity\Producto e 
        WHERE e.estado = :activo AND (e.codigo LIKE :src OR e.descripcion LIKE :src2) AND e.codigo <> :cod
        ORDER BY e.descripcion DESC')->setParameter(':activo','A')->setParameter(':src','%'.$src.'%')->setParameter(':src2','%'.$src.'%')->setParameter(':cod','000');

		return $query->getResult();
	}	
	public function predictivaprecio($src){
		$query = $this->getEntityManager()->createQuery('
        SELECT p
        FROM JOYAS\JoyasBundle\Entity\Producto e, JOYAS\JoyasBundle\Entity\Precio p
        WHERE e.estado = :activo AND e.id = p.producto AND (e.codigo LIKE :src OR e.descripcion LIKE :src2) AND e.codigo <> :cod
        ORDER BY e.descripcion DESC')->setParameter(':activo','A')->setParameter(':src','%'.$src.'%')->setParameter(':src2','%'.$src.'%')->setParameter(':cod','000');

		return $query->getResult();
	}	
}
