<?php

namespace JOYAS\JoyasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
	public function getAllActivas($unidad = NULL){
		if(isset($unidad)){
			$query = $this->getEntityManager()->createQuery('SELECT e FROM JOYAS\JoyasBundle\Entity\Usuario e WHERE e.estado = :activo AND e.unidadNegocio = :unidad ORDER BY e.login ASC')->setParameter(':activo','A')->setParameter(':unidad',$unidad);
		}else{
			$query = $this->getEntityManager()->createQuery('SELECT e FROM JOYAS\JoyasBundle\Entity\Usuario e WHERE e.estado = :activo ORDER BY e.login ASC')->setParameter(':activo','A');		
		}
		return $query->getResult();
	}
}
